version: '3.8'

services:
  fastapi:
    image: repo_name/price-discovery-fastapi:latest
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:8000"
    env_file:
      - .env

  streamlit:
    image: repo_name/price-discovery-streamlit:latest
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    env_file:
      - .env
